### ISSUE TITLE
Recording stops when the user pauses

### ISSUE THREAD

**Issue by jacksonmgrant** [jacksonmgrant/Scribe#10]
The recording should only stop when the user clicks the stop recording function. This is currently happening because the speech recognizer service is stopping after the first speech is recognized, which happens after the first sentence is spoken.

**Comment by junkshark8** [comment]
I set up the loading screen on the record function, but there's a bug where the loading screen goes on perpetually if the recording stops before the user clicks stop recording

**Comment by jacksonmgrant** [comment]
Long recordings are working now! Fixed the loading screen issues on recording by not needing it, the process happens faster than it takes the hook to pull up the loading screen.
