### ISSUE TITLE
Login button does not indicate user is logged in after refreshing

### ISSUE THREAD

**Issue by jacksonmgrant** [jacksonmgrant/Scribe#11]
When the page is refreshed while a user is logged in, the button that should read Log Out switches to Log In. It still works as intended, not a high priority, just something I noticed.

**Comment by junkshark8** [comment]
about us and form submission also disappear - it still works the same bc both Log In and Log Out link to the login page, but isSignIn must be resetting to false on refresh

**Comment by junkshark8** [comment]
i tried a fix for this and it caused more issues lol, might have time to work on it later
