### ISSUE TITLE
DB-setup branch's error

### ISSUE THREAD

**Issue by FordPipatkittikul** [jacksonmgrant/Scribe#16]
User cannot signup. Login still working but after user login, they do not have their previous note that they already uploaded. User cannot upload File as well.

**Comment by FordPipatkittikul** [comment]
Don't merge to the main one.

**Comment by junkshark8** [comment]
yup i still have some work to do on this

**Comment by junkshark8** [comment]
feedback form goes thru to the database but throws failed to fetch error on the fe

**Comment by junkshark8** [comment]
signup error fixed
