### ISSUE TITLE
Investigate: After an API call errors out, no other calls are sent unless the page refreshes

### ISSUE THREAD

**Issue by jacksonmgrant** [jacksonmgrant/Scribe#29]
Examples:
- Was working on get notes and it was returning a 400 and 500 at different points. After the error returned, no other operations (create, update, delete) worked unless the page was refreshed or a different page was loaded.
- When audio files were being sent on the multipartError branch, they were returning a 422. We needed to refresh the page in order to test again because uploading another file would not send an API request.

**Comment by FordPipatkittikul** [comment]
I might not fully understand the issues. but everytime I create I get 201 delete 200 and It seems like it working for me

**Comment by jacksonmgrant** [comment]
It works fine when you get a successful call, it's when  the call fails it seems to break. You'd have to go break something in the backend or force an error in the fe code to do it. I'm not sure if it's an intended feature of the frameworks we're using or not.
